### ISSUE TITLE
If < 5 columns defined, hansotable inserts a 5th colmn

### ISSUE THREAD

**Issue by nealmarques** [bobdenotter/gridviewfield#1]
If < 5 columns defined, hansotable inserts a 5th colmn

**Comment by bobdenotter** [comment]
As far as i can tell, this is a limitation of Handsontable. Is this problematic for you?

**Comment by SvanteRichter** [comment]
Isn't this configurable with the "minCols" property? it seems that way looking [at the docs](https://github.com/handsontable/handsontable/wiki/Options#column-options) but I have not tried it.

**Comment by bobdenotter** [comment]
fixed by #4
