### ISSUE TITLE
Compatibility with Bolt v3.3.6

### ISSUE THREAD

**Issue by nbehier** [bobdenotter/gridviewfield#15]
Today, I upgrade a website from `2.2.24` to `3.3.6` (follow the steps : new Bolt install, put my old config/theme/files/db, refresh db, reinstall extensions). 
I installed the gridfield extension `v1.1.1`.

One of my contenttype is defined as :
```        time_tracking:
            type: grid
            sorting: false
            rowheaders: true
            rowmove: false
            columns:
                date: Date
                duration: Temps passé
                type: Type
                desc: Détails
            height: 400
            group: Log
```

When I go to bolt admin, I see an empty grid field (even if there were some db data before for that entity). If I add some data and save entity, no error is displayed and grid display data. But If a refresh my admin, no data is included on grid (neither on front page).
I do not have JS error on chrome console.

Do you have any idea or test to help me to debug ?

**Comment by bobdenotter** [comment]
I just tagged version 1.1.2 that should fix this.

**Comment by nbehier** [comment]
Thanks a lot @bobdenotter… as usual!
