### ISSUE TITLE
Adding Multiple Grid View Fields to the same Content-type causes display issues in the admin.

### ISSUE THREAD

**Issue by nealmarques** [bobdenotter/gridviewfield#2]
Adding Multiple Grid View Fields to the same Content-type causes display issues in the admin.

Seems to be related to the fact that only one container id is set for handsometable. 

Fixed the issue with:

<div id="hot-{{key}}" style='width: 100%; border-right: 1px solid #DDD; border-bottom: 1px solid #DDD; background-color: #F8F8F8;'></div>

var container = document.getElementById('hot-{{key}}');

**Comment by bobdenotter** [comment]
Thanks, I'll fix that!
