### ISSUE TITLE
[BUG] Update Schema with error on NOT NULL Constraint

### ISSUE THREAD

**Issue by nbehier** [bobdenotter/gridviewfield#9]
I added a grid field on my `contenttypes.yml`. When I try to update my schema, I get an error for _NOT NULL constraint_ on `http://mysite/bolt/dbupdate` :

```
Bolt - Erreur fatale
Classe Doctrine\DBAL\Exception\DriverException
Message An exception occurred while executing 'ALTER TABLE bolt_projets ADD COLUMN time_tracking CLOB NOT NULL': SQLSTATE[HY000]: General error: 1 Cannot add a NOT NULL column with default value NULL
Code 0
```
## Details
- Relevant Bolt Version: 2.2.18
- Install type: Zip/tarball install
- PHP version: 5.6
- Used webserver: Apache
- Relevant Bolt Extension Version : bobdenotter/gridfield - v0.7.2

**Comment by SvanteRichter** [comment]
This is part of the fixes that are included in #8...

Nudge @bobdenotter

**Comment by bobdenotter** [comment]
I tagged a new `v0.8.0` release. Should be available in 30 minutes tops in the Bolt backend.

**Comment by nbehier** [comment]
Thanks to you two, it works perfectly !
